In [1]:
import numpy as np

**Matrix multiplication**

In [2]:
a = np.array([[1, -3, 2], [4, 0, -5]])
print(a)

[[ 1 -3  2]
 [ 4  0 -5]]


In [3]:
a.shape

(2, 3)

In [4]:
b = np.array([[3], [1], [2]])
print(b)

[[3]
 [1]
 [2]]


In [5]:
c = np.matmul(a, b)
print(c)

[[4]
 [2]]


In [6]:
d = np.dot(a, b)
print(d)

[[4]
 [2]]


In [7]:
d.shape

(2, 1)